version: '2'

services:
  opencv:
    build: .
    ports:
    - "8088:8080"
    volumes:
    - ./sample:/usr/local/src
    # environment:
    # - http_proxy=http://example.com:8080
    # - https_proxy=http://example.com:8080
    entrypoint: /bin/sh -c 'python server.py'
